### ISSUE TITLE
Header undefined

### ISSUE THREAD

**Issue by wlouckx** [wlouckx/aurorajs#8]
header.forEach(function(value, index){

                                   ^

TypeError: Cannot read property 'forEach' of undefined

    at IncomingMessage.<anonymous> (/usr/src/app/parser.js:133:36)

    at IncomingMessage.emit (events.js:327:22)

    at endReadableNT (_stream_readable.js:1201:12)

    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by MisterTFM** [comment]
@wlouckx have you done any recent work on integrating with Home Assistant?

**Comment by wlouckx** [comment]
@MisterTFM I haven't had the time anymore for this library and I've been using the [native aurora integration](https://www.home-assistant.io/integrations/aurora/) and a picture card for the oval:

```
 - type: picture
    image: >-
      https://services.swpc.noaa.gov/images/animations/ovation/north/latest.jpg?v={{now().timestamp()|int
      }}
```

**Comment by MisterTFM** [comment]
I'd like to see more info pulled 

IE:
     - SolarWindSpeed
      - SolarWindMagneticField
      - HemisphericPower
      - KIndex
      - EstimatedKIndex
      - SolarWindFlux

**Comment by wlouckx** [comment]
Sources of SWPC/NOAA are not always in a nice readable format, at least it wasn't a few years ago, so they each need their own translation function. Maybe I'll have time later this autumn, but I'm rather tempted to give a go at making a pull request for the native integration than maintaining this repository.

**Comment by MisterTFM** [comment]
I was able to successfully scrape the Solar Wind Speed data from the NOAA site from Home Assistant using a REST command.  Just need to look through all the NOAA json files to find the data I want.  I found this tool to help search thru the json files:  https://jsonpathfinder.com/
